apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-dep
  labels:
    name: amazon
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      name: amazon
  template:
    metadata:
      labels:
        name: amazon
    spec:
      containers:
      - name: amzon-clone
        image: praveenakumara/amazon:v1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: amazon-service
spec:
  type: NodePort
  selector:
      name: amazon
  ports:
    - nodePort: 32001
      targetPort: 3000
      port: 3000
